// Generated by scripts/build-glyph-presets.mjs — do not edit by hand.
//
// Each preset is a set of scanned marks and the twelve-level ramp solved
// for them. `peak` is the ink the darkest level asks for: it is a property
// of the set, because a set of airy letterpress cannot reach the coverage a
// solid woodblock does without overflowing its cells.

import type { GlyphSpec } from "./types";

export type Preset = {
  id: string;
  label: string;
  /** Ink coverage of the darkest level, 0..1. */
  peak: number;
  /** Size ceiling in cells that the levels below were solved against. */
  maxSize: number;
  glyphs: GlyphSpec[];
  /** Mark ids per level, lightest first. The first of each is the ramp's reference. */
  levels: string[][];
  /**
   * Ink density and proportion of each mark, measured at build time.
   *
   * The browser measures every mark again on load and *that* is what the
   * renderer uses; these are here so the levels can be checked without a
   * canvas — that no mark overflows its cell, that the ladder climbs.
   *
   * The two measure the same thing off the same pixels and agree to within
   * a fraction of a percent, which is far below the step between levels.
   * They are not identical: the browser re-rasterizes each mark to 256 px
   * with its own resampler first.
   */
  metrics: Record<string, { density: number; aspect: number }>;
};

export const presetLevels = 12;
export const presetMaxSize = 1.15;

export const presets: Preset[] = [
  {
    id: "eighteenth-century",
    label: "18th century",
    peak: 0.4439,
    maxSize: 1.15,
    glyphs: [
      { id: "preset-eighteenth-century-01", label: "18th century 01", kind: "preset", source: "presets/eighteenth-century/01.webp" },
      { id: "preset-eighteenth-century-02", label: "18th century 02", kind: "preset", source: "presets/eighteenth-century/02.webp" },
      { id: "preset-eighteenth-century-03", label: "18th century 03", kind: "preset", source: "presets/eighteenth-century/03.webp" },
      { id: "preset-eighteenth-century-04", label: "18th century 04", kind: "preset", source: "presets/eighteenth-century/04.webp" },
      { id: "preset-eighteenth-century-05", label: "18th century 05", kind: "preset", source: "presets/eighteenth-century/05.webp" },
      { id: "preset-eighteenth-century-06", label: "18th century 06", kind: "preset", source: "presets/eighteenth-century/06.webp" },
      { id: "preset-eighteenth-century-07", label: "18th century 07", kind: "preset", source: "presets/eighteenth-century/07.webp" },
      { id: "preset-eighteenth-century-11", label: "18th century 11", kind: "preset", source: "presets/eighteenth-century/11.webp" },
      { id: "preset-eighteenth-century-12", label: "18th century 12", kind: "preset", source: "presets/eighteenth-century/12.webp" },
      { id: "preset-eighteenth-century-13", label: "18th century 13", kind: "preset", source: "presets/eighteenth-century/13.webp" },
      { id: "preset-eighteenth-century-14", label: "18th century 14", kind: "preset", source: "presets/eighteenth-century/14.webp" },
      { id: "preset-eighteenth-century-15", label: "18th century 15", kind: "preset", source: "presets/eighteenth-century/15.webp" },
      { id: "preset-eighteenth-century-16", label: "18th century 16", kind: "preset", source: "presets/eighteenth-century/16.webp" },
      { id: "preset-eighteenth-century-17", label: "18th century 17", kind: "preset", source: "presets/eighteenth-century/17.webp" },
      { id: "preset-eighteenth-century-18", label: "18th century 18", kind: "preset", source: "presets/eighteenth-century/18.webp" },
      { id: "preset-eighteenth-century-19", label: "18th century 19", kind: "preset", source: "presets/eighteenth-century/19.webp" },
      { id: "preset-eighteenth-century-20", label: "18th century 20", kind: "preset", source: "presets/eighteenth-century/20.webp" },
      { id: "preset-eighteenth-century-21", label: "18th century 21", kind: "preset", source: "presets/eighteenth-century/21.webp" },
      { id: "preset-eighteenth-century-22", label: "18th century 22", kind: "preset", source: "presets/eighteenth-century/22.webp" },
      { id: "preset-eighteenth-century-23", label: "18th century 23", kind: "preset", source: "presets/eighteenth-century/23.webp" },
      { id: "preset-eighteenth-century-41", label: "18th century 41", kind: "preset", source: "presets/eighteenth-century/41.webp" },
      { id: "preset-eighteenth-century-42", label: "18th century 42", kind: "preset", source: "presets/eighteenth-century/42.webp" },
      { id: "preset-eighteenth-century-51", label: "18th century 51", kind: "preset", source: "presets/eighteenth-century/51.webp" },
      { id: "preset-eighteenth-century-52", label: "18th century 52", kind: "preset", source: "presets/eighteenth-century/52.webp" },
    ],
    levels: [
      ["preset-eighteenth-century-13", "preset-eighteenth-century-19"],
      ["preset-eighteenth-century-12", "preset-eighteenth-century-52"],
      ["preset-eighteenth-century-11", "preset-eighteenth-century-41"],
      ["preset-eighteenth-century-02", "preset-eighteenth-century-22"],
      ["preset-eighteenth-century-06", "preset-eighteenth-century-17"],
      ["preset-eighteenth-century-22", "preset-eighteenth-century-02"],
      ["preset-eighteenth-century-07", "preset-eighteenth-century-03"],
      ["preset-eighteenth-century-15", "preset-eighteenth-century-51"],
      ["preset-eighteenth-century-22", "preset-eighteenth-century-42"],
      ["preset-eighteenth-century-17", "preset-eighteenth-century-18", "preset-eighteenth-century-05", "preset-eighteenth-century-20"],
      ["preset-eighteenth-century-18", "preset-eighteenth-century-05", "preset-eighteenth-century-07", "preset-eighteenth-century-20"],
      ["preset-eighteenth-century-20", "preset-eighteenth-century-05", "preset-eighteenth-century-07", "preset-eighteenth-century-23"],
    ],
    metrics: {
      "preset-eighteenth-century-01": { density: 0.20382, aspect: 1.43820 },
      "preset-eighteenth-century-02": { density: 0.35243, aspect: 0.42857 },
      "preset-eighteenth-century-03": { density: 0.35629, aspect: 0.52128 },
      "preset-eighteenth-century-04": { density: 0.25397, aspect: 1.32653 },
      "preset-eighteenth-century-05": { density: 0.62587, aspect: 0.64286 },
      "preset-eighteenth-century-06": { density: 0.40066, aspect: 0.40000 },
      "preset-eighteenth-century-07": { density: 0.42607, aspect: 0.80952 },
      "preset-eighteenth-century-11": { density: 0.13295, aspect: 0.98485 },
      "preset-eighteenth-century-12": { density: 0.10719, aspect: 2.22807 },
      "preset-eighteenth-century-13": { density: 0.18015, aspect: 2.02500 },
      "preset-eighteenth-century-14": { density: 0.23497, aspect: 1.29032 },
      "preset-eighteenth-century-15": { density: 0.22658, aspect: 1.09524 },
      "preset-eighteenth-century-16": { density: 0.22785, aspect: 0.75000 },
      "preset-eighteenth-century-17": { density: 0.33229, aspect: 0.80000 },
      "preset-eighteenth-century-18": { density: 0.31037, aspect: 0.94444 },
      "preset-eighteenth-century-19": { density: 0.19611, aspect: 1.42105 },
      "preset-eighteenth-century-20": { density: 0.46089, aspect: 0.89655 },
      "preset-eighteenth-century-21": { density: 0.19724, aspect: 1.28571 },
      "preset-eighteenth-century-22": { density: 0.25729, aspect: 0.85714 },
      "preset-eighteenth-century-23": { density: 0.36354, aspect: 1.00806 },
      "preset-eighteenth-century-41": { density: 0.16068, aspect: 1.59184 },
      "preset-eighteenth-century-42": { density: 0.22659, aspect: 0.97778 },
      "preset-eighteenth-century-51": { density: 0.32320, aspect: 0.55263 },
      "preset-eighteenth-century-52": { density: 0.27456, aspect: 3.21429 },
    },
  },
  {
    id: "eighteen-twelve",
    label: "1812",
    peak: 0.3004,
    maxSize: 1.15,
    glyphs: [
      { id: "preset-eighteen-twelve-01", label: "1812 01", kind: "preset", source: "presets/eighteen-twelve/01.webp" },
      { id: "preset-eighteen-twelve-02", label: "1812 02", kind: "preset", source: "presets/eighteen-twelve/02.webp" },
      { id: "preset-eighteen-twelve-03", label: "1812 03", kind: "preset", source: "presets/eighteen-twelve/03.webp" },
      { id: "preset-eighteen-twelve-04", label: "1812 04", kind: "preset", source: "presets/eighteen-twelve/04.webp" },
      { id: "preset-eighteen-twelve-05", label: "1812 05", kind: "preset", source: "presets/eighteen-twelve/05.webp" },
      { id: "preset-eighteen-twelve-06", label: "1812 06", kind: "preset", source: "presets/eighteen-twelve/06.webp" },
      { id: "preset-eighteen-twelve-07", label: "1812 07", kind: "preset", source: "presets/eighteen-twelve/07.webp" },
      { id: "preset-eighteen-twelve-08", label: "1812 08", kind: "preset", source: "presets/eighteen-twelve/08.webp" },
      { id: "preset-eighteen-twelve-09", label: "1812 09", kind: "preset", source: "presets/eighteen-twelve/09.webp" },
      { id: "preset-eighteen-twelve-10", label: "1812 10", kind: "preset", source: "presets/eighteen-twelve/10.webp" },
      { id: "preset-eighteen-twelve-12", label: "1812 12", kind: "preset", source: "presets/eighteen-twelve/12.webp" },
      { id: "preset-eighteen-twelve-13", label: "1812 13", kind: "preset", source: "presets/eighteen-twelve/13.webp" },
      { id: "preset-eighteen-twelve-14", label: "1812 14", kind: "preset", source: "presets/eighteen-twelve/14.webp" },
      { id: "preset-eighteen-twelve-15", label: "1812 15", kind: "preset", source: "presets/eighteen-twelve/15.webp" },
      { id: "preset-eighteen-twelve-16", label: "1812 16", kind: "preset", source: "presets/eighteen-twelve/16.webp" },
    ],
    levels: [
      ["preset-eighteen-twelve-07", "preset-eighteen-twelve-10"],
      ["preset-eighteen-twelve-13", "preset-eighteen-twelve-09"],
      ["preset-eighteen-twelve-13", "preset-eighteen-twelve-09"],
      ["preset-eighteen-twelve-10", "preset-eighteen-twelve-08"],
      ["preset-eighteen-twelve-12", "preset-eighteen-twelve-02"],
      ["preset-eighteen-twelve-07", "preset-eighteen-twelve-03"],
      ["preset-eighteen-twelve-12", "preset-eighteen-twelve-14"],
      ["preset-eighteen-twelve-04", "preset-eighteen-twelve-06"],
      ["preset-eighteen-twelve-16", "preset-eighteen-twelve-05"],
      ["preset-eighteen-twelve-14", "preset-eighteen-twelve-06", "preset-eighteen-twelve-01", "preset-eighteen-twelve-15"],
      ["preset-eighteen-twelve-16", "preset-eighteen-twelve-04", "preset-eighteen-twelve-05", "preset-eighteen-twelve-03"],
      ["preset-eighteen-twelve-05", "preset-eighteen-twelve-03", "preset-eighteen-twelve-06", "preset-eighteen-twelve-15"],
    ],
    metrics: {
      "preset-eighteen-twelve-01": { density: 0.18806, aspect: 1.11864 },
      "preset-eighteen-twelve-02": { density: 0.13598, aspect: 1.10891 },
      "preset-eighteen-twelve-03": { density: 0.33484, aspect: 1.23529 },
      "preset-eighteen-twelve-04": { density: 0.27746, aspect: 1.29630 },
      "preset-eighteen-twelve-05": { density: 0.33187, aspect: 0.95833 },
      "preset-eighteen-twelve-06": { density: 0.36770, aspect: 0.75000 },
      "preset-eighteen-twelve-07": { density: 0.26236, aspect: 3.21429 },
      "preset-eighteen-twelve-08": { density: 0.19925, aspect: 1.12281 },
      "preset-eighteen-twelve-09": { density: 0.13991, aspect: 2.25806 },
      "preset-eighteen-twelve-10": { density: 0.14001, aspect: 1.46667 },
      "preset-eighteen-twelve-12": { density: 0.17780, aspect: 0.62963 },
      "preset-eighteen-twelve-13": { density: 0.17697, aspect: 2.90909 },
      "preset-eighteen-twelve-14": { density: 0.27407, aspect: 1.54167 },
      "preset-eighteen-twelve-15": { density: 0.30341, aspect: 1.34783 },
      "preset-eighteen-twelve-16": { density: 0.28414, aspect: 0.82143 },
    },
  },
  {
    id: "great-war",
    label: "Great War",
    peak: 0.5384,
    maxSize: 1.15,
    glyphs: [
      { id: "preset-great-war-01", label: "Great War 01", kind: "preset", source: "presets/great-war/01.webp" },
      { id: "preset-great-war-02", label: "Great War 02", kind: "preset", source: "presets/great-war/02.webp" },
      { id: "preset-great-war-03", label: "Great War 03", kind: "preset", source: "presets/great-war/03.webp" },
      { id: "preset-great-war-04", label: "Great War 04", kind: "preset", source: "presets/great-war/04.webp" },
      { id: "preset-great-war-05", label: "Great War 05", kind: "preset", source: "presets/great-war/05.webp" },
      { id: "preset-great-war-06", label: "Great War 06", kind: "preset", source: "presets/great-war/06.webp" },
      { id: "preset-great-war-07", label: "Great War 07", kind: "preset", source: "presets/great-war/07.webp" },
      { id: "preset-great-war-08", label: "Great War 08", kind: "preset", source: "presets/great-war/08.webp" },
      { id: "preset-great-war-09", label: "Great War 09", kind: "preset", source: "presets/great-war/09.webp" },
      { id: "preset-great-war-10", label: "Great War 10", kind: "preset", source: "presets/great-war/10.webp" },
      { id: "preset-great-war-11", label: "Great War 11", kind: "preset", source: "presets/great-war/11.webp" },
      { id: "preset-great-war-12", label: "Great War 12", kind: "preset", source: "presets/great-war/12.webp" },
      { id: "preset-great-war-13", label: "Great War 13", kind: "preset", source: "presets/great-war/13.webp" },
      { id: "preset-great-war-14", label: "Great War 14", kind: "preset", source: "presets/great-war/14.webp" },
    ],
    levels: [
      ["preset-great-war-14", "preset-great-war-02"],
      ["preset-great-war-02", "preset-great-war-10"],
      ["preset-great-war-14", "preset-great-war-01"],
      ["preset-great-war-03", "preset-great-war-14"],
      ["preset-great-war-12", "preset-great-war-01"],
      ["preset-great-war-02", "preset-great-war-13"],
      ["preset-great-war-06", "preset-great-war-05"],
      ["preset-great-war-13", "preset-great-war-10"],
      ["preset-great-war-07", "preset-great-war-09"],
      ["preset-great-war-05", "preset-great-war-04", "preset-great-war-08", "preset-great-war-11"],
      ["preset-great-war-07", "preset-great-war-09", "preset-great-war-06", "preset-great-war-11"],
      ["preset-great-war-07", "preset-great-war-06", "preset-great-war-08", "preset-great-war-11"],
    ],
    metrics: {
      "preset-great-war-01": { density: 0.33381, aspect: 1.33333 },
      "preset-great-war-02": { density: 0.32831, aspect: 1.25490 },
      "preset-great-war-03": { density: 0.36904, aspect: 1.23077 },
      "preset-great-war-04": { density: 0.41235, aspect: 1.23077 },
      "preset-great-war-05": { density: 0.42166, aspect: 0.99219 },
      "preset-great-war-06": { density: 0.54388, aspect: 1.14286 },
      "preset-great-war-07": { density: 0.59604, aspect: 1.00000 },
      "preset-great-war-08": { density: 0.59589, aspect: 0.72115 },
      "preset-great-war-09": { density: 0.60291, aspect: 0.69000 },
      "preset-great-war-10": { density: 0.37710, aspect: 1.06723 },
      "preset-great-war-11": { density: 0.46567, aspect: 0.84127 },
      "preset-great-war-12": { density: 0.32782, aspect: 1.15596 },
      "preset-great-war-13": { density: 0.36191, aspect: 0.91509 },
      "preset-great-war-14": { density: 0.15283, aspect: 1.04098 },
    },
  },
  {
    id: "nineteen-forty-one",
    label: "1941",
    peak: 0.6264,
    maxSize: 1.15,
    glyphs: [
      { id: "preset-nineteen-forty-one-01", label: "1941 01", kind: "preset", source: "presets/nineteen-forty-one/01.webp" },
      { id: "preset-nineteen-forty-one-02", label: "1941 02", kind: "preset", source: "presets/nineteen-forty-one/02.webp" },
      { id: "preset-nineteen-forty-one-03", label: "1941 03", kind: "preset", source: "presets/nineteen-forty-one/03.webp" },
      { id: "preset-nineteen-forty-one-04", label: "1941 04", kind: "preset", source: "presets/nineteen-forty-one/04.webp" },
      { id: "preset-nineteen-forty-one-05", label: "1941 05", kind: "preset", source: "presets/nineteen-forty-one/05.webp" },
      { id: "preset-nineteen-forty-one-06", label: "1941 06", kind: "preset", source: "presets/nineteen-forty-one/06.webp" },
      { id: "preset-nineteen-forty-one-07", label: "1941 07", kind: "preset", source: "presets/nineteen-forty-one/07.webp" },
      { id: "preset-nineteen-forty-one-08", label: "1941 08", kind: "preset", source: "presets/nineteen-forty-one/08.webp" },
      { id: "preset-nineteen-forty-one-09", label: "1941 09", kind: "preset", source: "presets/nineteen-forty-one/09.webp" },
      { id: "preset-nineteen-forty-one-10", label: "1941 10", kind: "preset", source: "presets/nineteen-forty-one/10.webp" },
      { id: "preset-nineteen-forty-one-11", label: "1941 11", kind: "preset", source: "presets/nineteen-forty-one/11.webp" },
      { id: "preset-nineteen-forty-one-12", label: "1941 12", kind: "preset", source: "presets/nineteen-forty-one/12.webp" },
      { id: "preset-nineteen-forty-one-13", label: "1941 13", kind: "preset", source: "presets/nineteen-forty-one/13.webp" },
      { id: "preset-nineteen-forty-one-14", label: "1941 14", kind: "preset", source: "presets/nineteen-forty-one/14.webp" },
      { id: "preset-nineteen-forty-one-15", label: "1941 15", kind: "preset", source: "presets/nineteen-forty-one/15.webp" },
      { id: "preset-nineteen-forty-one-16", label: "1941 16", kind: "preset", source: "presets/nineteen-forty-one/16.webp" },
      { id: "preset-nineteen-forty-one-17", label: "1941 17", kind: "preset", source: "presets/nineteen-forty-one/17.webp" },
    ],
    levels: [
      ["preset-nineteen-forty-one-17", "preset-nineteen-forty-one-09"],
      ["preset-nineteen-forty-one-06", "preset-nineteen-forty-one-04"],
      ["preset-nineteen-forty-one-04", "preset-nineteen-forty-one-06"],
      ["preset-nineteen-forty-one-17", "preset-nineteen-forty-one-10"],
      ["preset-nineteen-forty-one-09", "preset-nineteen-forty-one-16"],
      ["preset-nineteen-forty-one-08", "preset-nineteen-forty-one-02"],
      ["preset-nineteen-forty-one-07", "preset-nineteen-forty-one-05"],
      ["preset-nineteen-forty-one-10", "preset-nineteen-forty-one-14"],
      ["preset-nineteen-forty-one-13", "preset-nineteen-forty-one-11"],
      ["preset-nineteen-forty-one-02", "preset-nineteen-forty-one-08", "preset-nineteen-forty-one-03", "preset-nineteen-forty-one-12"],
      ["preset-nineteen-forty-one-15", "preset-nineteen-forty-one-07", "preset-nineteen-forty-one-14", "preset-nineteen-forty-one-01"],
      ["preset-nineteen-forty-one-01", "preset-nineteen-forty-one-12", "preset-nineteen-forty-one-14", "preset-nineteen-forty-one-13"],
    ],
    metrics: {
      "preset-nineteen-forty-one-01": { density: 0.62490, aspect: 0.96032 },
      "preset-nineteen-forty-one-02": { density: 0.49962, aspect: 1.32353 },
      "preset-nineteen-forty-one-03": { density: 0.51602, aspect: 0.67416 },
      "preset-nineteen-forty-one-04": { density: 0.11146, aspect: 0.84252 },
      "preset-nineteen-forty-one-05": { density: 0.42891, aspect: 0.74324 },
      "preset-nineteen-forty-one-06": { density: 0.24738, aspect: 4.07407 },
      "preset-nineteen-forty-one-07": { density: 0.49032, aspect: 1.24138 },
      "preset-nineteen-forty-one-08": { density: 0.38367, aspect: 1.05263 },
      "preset-nineteen-forty-one-09": { density: 0.36071, aspect: 1.50000 },
      "preset-nineteen-forty-one-10": { density: 0.34542, aspect: 0.98077 },
      "preset-nineteen-forty-one-11": { density: 0.39345, aspect: 1.21622 },
      "preset-nineteen-forty-one-12": { density: 0.59460, aspect: 0.85156 },
      "preset-nineteen-forty-one-13": { density: 0.54172, aspect: 0.89844 },
      "preset-nineteen-forty-one-14": { density: 0.65743, aspect: 0.86719 },
      "preset-nineteen-forty-one-15": { density: 0.43479, aspect: 1.00000 },
      "preset-nineteen-forty-one-16": { density: 0.20739, aspect: 1.04167 },
      "preset-nineteen-forty-one-17": { density: 0.19409, aspect: 1.17241 },
    },
  },
];

/** Every shipped mark id, for validating untrusted project files. */
export const presetGlyphIds = new Set(presets.flatMap(
  (preset) => preset.glyphs.map((glyph) => glyph.id),
));
