import type { Preset } from "./types";

export const presets: Preset[] = [
  {
    name: "Receipt scan",
    description: "Hard thermal threshold with narrow scanner bands.",
    settings: {
      printMode: "dither",
      levels: 2,
      contrast: 1.65,
      gamma: 1.15,
      noise: 0.04,
      paper: 0.18,
      banding: 0.16,
      chaos: 0.22,
    },
  },
  {
    name: "Riso duotone",
    description: "Coarse dots and visible frame-to-frame registration.",
    settings: {
      printMode: "halftone",
      halftoneScale: 9,
      dotGain: 0.18,
      contrast: 1.25,
      noise: 0.03,
      paper: 0.08,
      chaos: 0.48,
    },
  },
  {
    name: "Xerox 3rd generation",
    description: "Crushed values, noise, and unstable paper feed.",
    settings: {
      printMode: "dither",
      levels: 3,
      threshold: 0.46,
      contrast: 1.8,
      gamma: 1.2,
      noise: 0.2,
      paper: 0.12,
      banding: 0.2,
      chaos: 0.7,
    },
  },
  {
    name: "Newsprint halftone",
    description: "Large newspaper dots with soft paper.",
    settings: {
      printMode: "halftone",
      halftoneScale: 7,
      dotGain: 0.08,
      contrast: 1.1,
      gamma: 1.05,
      noise: 0.05,
      paper: 0.2,
      chaos: 0.25,
    },
  },
  {
    name: "Fax 1994",
    description: "One-bit threshold, coarse noise, and horizontal loss.",
    settings: {
      printMode: "dither",
      levels: 2,
      threshold: 0.57,
      contrast: 2.15,
      gamma: 1.3,
      noise: 0.16,
      noiseSize: 3,
      banding: 0.25,
      chaos: 0.55,
    },
  },
  {
    name: "Clean 1-bit",
    description: "A restrained black-and-white ordered dither.",
    settings: {
      printMode: "dither",
      levels: 2,
      threshold: 0.5,
      contrast: 1.05,
      gamma: 1,
      noise: 0,
      paper: 0,
      banding: 0,
      chaos: 0,
    },
  },
];
