// Convert the counter alphabet to outlines using macOS CoreText. No extra modules.
// Usage: swift scripts/build-reaction-type.swift /path/to/Roboto-Medium.ttf
// The output is the complete generatedReactionType.ts source on stdout.
import Foundation
import CoreText

guard CommandLine.arguments.count == 2,
      let provider = CGDataProvider(url: URL(fileURLWithPath: CommandLine.arguments[1]) as CFURL),
      let graphics = CGFont(provider) else {
  fatalError("Pass the official Roboto-Medium.ttf font file.")
}
let font = CTFontCreateWithGraphicsFont(graphics, 100, nil, nil)
func n(_ value: CGFloat) -> String {
  String(format: "%.3f", locale: Locale(identifier: "en_US_POSIX"), Double(value))
}
var alphabet: [String: Any] = [:]
for character in "0123456789,k" {
  var code = character.utf16.first!
  var glyph: CGGlyph = 0
  guard CTFontGetGlyphsForCharacters(font, &code, &glyph, 1),
        let path = CTFontCreatePathForGlyph(font, glyph, nil) else {
    fatalError("Missing glyph: \(character)")
  }
  var advance = CGSize.zero
  CTFontGetAdvancesForGlyphs(font, .horizontal, &glyph, &advance, 1)
  var data = ""
  func point(_ p: CGPoint) -> String { "\(n(p.x)) \(n(-p.y))" }
  path.applyWithBlock { element in
    let e = element.pointee
    switch e.type {
    case .moveToPoint: data += "M\(point(e.points[0]))"
    case .addLineToPoint: data += "L\(point(e.points[0]))"
    case .addQuadCurveToPoint: data += "Q\(point(e.points[0])) \(point(e.points[1]))"
    case .addCurveToPoint: data += "C\(point(e.points[0])) \(point(e.points[1])) \(point(e.points[2]))"
    case .closeSubpath: data += "Z"
    @unknown default: fatalError("Unknown path command")
    }
  }
  alphabet[String(character)] = ["path": data, "advance": Double(advance.width)]
}
let json = try JSONSerialization.data(withJSONObject: alphabet, options: [.sortedKeys, .prettyPrinted])
print("// Generated by scripts/build-reaction-type.swift from Roboto Medium.")
print("// Copyright 2011 Google Inc. Apache-2.0; see public/licenses/roboto.txt.")
print("// Modified: counter alphabet only, converted to SVG paths at 100 font units.")
print("export const reactionType: Record<string, { path: string; advance: number }> = " + String(data: json, encoding: .utf8)! + ";")
