/** Preserve the owner's trace as absolute curves, not a raster retrace. */
import { readFileSync } from "node:fs";
import { optimize } from "svgo";
import { parsePathData } from "../node_modules/svgo/lib/path.js";

const source = readFileSync(new URL("../apps/glyph-art/src/assets/press-f.svg", import.meta.url), "utf8");
const svg = optimize(source, { plugins: ["convertShapeToPath"] }).data;
const [, viewBox] = /viewBox="([^"]+)"/.exec(svg);
const [x, y, width, height] = viewBox.split(/\s+/).map(Number);
if (x !== 0 || y !== 0 || !width || !height || /transform=|stroke=/.test(svg)) {
  throw new Error("The owner trace must use an untransformed zero-origin viewBox and filled paths.");
}
const n = (value) => Number(value.toFixed(5));
let output = "";
for (const [, data] of svg.matchAll(/<path\b[^>]*\bd="([^"]+)"/g)) {
  let at = [0, 0];
  let start = at;
  let previous = "";
  let control = at;
  for (const { command, args } of parsePathData(data)) {
    const relative = command === command.toLowerCase();
    const point = (index) => [args[index] + (relative ? at[0] : 0), args[index + 1] + (relative ? at[1] : 0)];
    const kind = command.toUpperCase();
    if (kind === "Z") {
      at = start;
      output += "Z";
    } else if (kind === "M" || kind === "L" || kind === "H" || kind === "V") {
      at = kind === "H" ? [args[0] + (relative ? at[0] : 0), at[1]]
        : kind === "V" ? [at[0], args[0] + (relative ? at[1] : 0)] : point(0);
      output += `${kind === "M" ? "M" : "L"}${at.map(n).join(" ")}`;
      if (kind === "M") start = at;
    } else if (kind === "C" || kind === "S") {
      const first = kind === "C" ? point(0) : previous === "C" || previous === "S"
        ? [at[0] * 2 - control[0], at[1] * 2 - control[1]] : at;
      const second = point(kind === "C" ? 2 : 0);
      const end = point(kind === "C" ? 4 : 2);
      output += `C${[...first, ...second, ...end].map(n).join(" ")}`;
      at = end;
      control = second;
    } else {
      throw new Error(`Unsupported command in the owner trace: ${command}`);
    }
    previous = kind;
  }
}
console.log("// Generated by scripts/build-press-f.mjs from the owner's Asset 1.svg.");
console.log("// Geometry is preserved; shorthand and relative commands are expanded.");
console.log(`export const pressFVector = ${JSON.stringify({ width, height, path: output }, null, 2)};`);
